# Generated by Django 5.0.1 on 2024-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=550)),
                ('isActivated', models.BooleanField()),
                ('isVerified', models.BooleanField()),
            ],
        ),
    ]
