# Generated by Django 5.0.1 on 2024-01-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatterloopscraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='ChatterloopUsers',
        ),
    ]
